server: 
  port: 9008
spring: 
  application:  
    name: tensquare-user #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.108.53.77:3306/tensquare_user?characterEncoding=UTF8
    username: root
    password: 123456
  jpa: 
    database: MySQL
    show-sql: true
  redis:
    host: 39.108.53.77
  rabbitmq:
    host: 39.108.53.77
jwt:
  config:
     key: itcast
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
  instance:
    prefer-ip-address: true
